Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatString:
  EnforcedStyle: sprintf
Style/FormatStringToken:
  EnforcedStyle: unannotated
