[package]
name = "clasm_compiler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clasp_common = { path = "../common" }

# This is for parsing hexadecimal numbers
hex = "0.4.3"
